// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using Robust.Client.Graphics;
using Robust.Client.GameObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Shared.Map;
using Content.Client.Eye;
using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.Surveillance.UI;

namespace Content.Client._Lua.Surveillance.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceMonitorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly TransformSystem _transform;
    private readonly EyeLerpingSystem _eyeLerping;

    private static readonly SpriteSpecifier.Texture BlipIcon = new(new("/Textures/Interface/NavMap/beveled_hexagon.png"));
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";

    private static readonly Vector2i ViewportSize = new(350, 350);
    private static readonly FixedEye DefaultEye = new();
    private readonly Texture _blipTexture;

    private EntityUid? _currentCamera;

    public event Action<NetEntity?>? CameraSelected;
    public event Action<NetEntity?>? GridSelected;
    public event Action? UpdateGridList;

    public SurveillanceMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _transform = _entity.System<TransformSystem>();
        _eyeLerping = _entity.System<EyeLerpingSystem>();

        _blipTexture = _entity.System<SpriteSystem>().GetTexture(BlipIcon);

        CameraViewBackground.ShaderOverride = _prototype.Index(CameraStaticShader).Instance();
        CameraView.ViewportSize = ViewportSize;
        CameraView.Eye = DefaultEye;

        UpdateGridsButton.OnPressed += _ => UpdateGridList?.Invoke();
        NavMap.TrackedEntitySelectedAction += args => CameraSelected?.Invoke(args);

        OnResized += () =>
        {
            NavMap.SetSize = Size;
            NavMap.ForceNavMapUpdate();
        };

        GridSelector.OnItemSelected += args =>
        {
            GridSelector.SelectId(args.Id);

            if (GridSelector.GetItemMetadata(args.Id) is NetEntity grid)
            {
                GridSelected?.Invoke(grid);
            }
        };
    }

    public void UpdateState(SurveillanceMonitorWindowInterfaceState state)
    {
        UpdateGridSelector(state.Grids, state.MultiGrid);
        UpdateEye(state.ActiveCamera, state.Connecting);
        UpdateNavMap(state.ActiveCamera, state.ActiveGrid, state.Cameras);
    }

    private void UpdateEye(NetEntity? netNewCamera, bool connecting)
    {
        if (_currentCamera != null)
        {
            _eyeLerping.RemoveEye(_currentCamera.Value);
            _currentCamera = null;
        }

        CameraView.Visible = false;
        CameraView.Eye = DefaultEye;
        CameraViewLoadingLabel.Visible = connecting;

        if (!_entity.TryGetEntity(netNewCamera, out var newCamera))
        {
            return;
        }

        CameraView.Visible = !connecting;

        _eyeLerping.AddEye(newCamera.Value);
        _currentCamera = newCamera;

        if (_entity.TryGetComponent<EyeComponent>(newCamera.Value, out var cameraEye))
        {
            CameraView.Eye = cameraEye.Eye;
        }
    }

    private void UpdateGridSelector(HashSet<NetEntity> grids, bool multiGrid)
    {
        UpdateGridsButton.Visible = multiGrid;

        if (!multiGrid)
        {
            GridSelector.Prefix = string.Empty;
            GridSelector.Clear();

            if (!grids.TryFirstOrNull(out var first)
                || !_entity.TryGetEntity(first, out var gridUid)
                || !_entity.TryGetComponent<MetaDataComponent>(gridUid, out var metaData))
            {
                return;
            }

            GridSelector.AddItem(Loc.GetString(metaData.EntityName));
            GridSelector.SelectId(0);
            return;
        }

        var previousSelected = GridSelector.SelectedId;
        GridSelector.Prefix = Loc.GetString("surveillance-monitor-grid-selector-prefix");
        GridSelector.Clear();

        foreach (var grid in grids)
        {
            if (!_entity.TryGetEntity(grid, out var gridUid)
                || !_entity.TryGetComponent<MetaDataComponent>(gridUid, out var metaData))
            {
                continue;
            }

            GridSelector.AddItem(Loc.GetString(metaData.EntityName));
            GridSelector.SetItemMetadata(GridSelector.ItemCount - 1, grid);
        }

        var outOfIndex = previousSelected >= GridSelector.ItemCount;
        GridSelector.SelectId(outOfIndex ? 0 : previousSelected);
    }

    private void UpdateNavMap(NetEntity? activeCamera, NetEntity? netActiveGrid, List<(NetEntity, NetCoordinates)>? cameras)
    {
        NavMap.TrackedEntities.Clear();

        if (cameras == null
            || !_entity.TryGetEntity(netActiveGrid, out var gridUid))
        {
            return;
        }

        NavMap.MapUid = gridUid;

        foreach (var (netCamera, netCoordinates) in cameras)
        {
            var coordinates = _entity.GetCoordinates(netCoordinates);
            var mapUid = _transform.GetMap(coordinates);

            if (mapUid != null)
            {
                coordinates = _transform.WithEntityId(coordinates, mapUid.Value);
            }

            var data = new NavMapBlip(coordinates, _blipTexture, Color.Yellow, netCamera == activeCamera);
            NavMap.TrackedEntities[netCamera] = data;
        }

        NavMap.ForceNavMapUpdate();
    }
}

public sealed class SurveillanceNavMapControl : NavMapControl
{
    public SurveillanceNavMapControl() : base()
    {
        WallColor = new(222, 92, 70);
        TileColor = new(105, 50, 30);
    }
}
