using Content.Shared.StationRecords;
using Robust.Shared.Prototypes; // Lua
using Robust.Client.GameObjects; // Lua
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralRecord : Control
{
    [Dependency] IEntityManager _entity = default!; // Lua
    [Dependency] IPrototypeManager _prototype = default!; // Lua

    public Action<uint>? OnDeletePressed;
    public GeneralRecord(GeneralStationRecord record, bool canDelete, uint? id)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Lua

        RecordName.Text = record.Name;
        Age.Text = Loc.GetString("general-station-record-console-record-age", ("age", record.Age.ToString()));
        Job.Text = Loc.GetString(record.JobTitle); // Lua
        JobIcon.Texture = _entity.System<SpriteSystem>().Frame0(_prototype.Index(record.JobIcon).Icon); // Lua
        Species.Text = Loc.GetString("general-station-record-console-record-species", ("species", record.Species));
        Gender.Text = Loc.GetString("general-station-record-console-record-gender",
            ("gender", record.Gender.ToString()));
        Fingerprint.Text = Loc.GetString("general-station-record-console-record-fingerprint",
            ("fingerprint", record.Fingerprint ?? Loc.GetString("generic-not-available-shorthand")));
        Dna.Text = Loc.GetString("general-station-record-console-record-dna",
            ("dna", record.DNA ?? Loc.GetString("generic-not-available-shorthand")));

        if (canDelete && id != null )
        {
            DeleteButton.Visible = true;
            DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(id.Value);
        }
    }
}
